name: SZCommands
version: 1.0-SNAPSHOT
main: szcommands.szcommands.SZCommands
authors: [RafaelFaustini]
website: www.rafaelfaustini.com.br
commands:
  god:
    description: Triggers your vulnerability
    aliases: [invulnerable,invincible,deus,invencivel,invencível,invulnerabel,imortal]
