name: SZCommands
version: 1.0-SNAPSHOT
main: szcommands.szcommands.SZCommands
authors: [RafaelFaustini]
website: www.rafaelfaustini.com.br
commands:
  god:
    description: Triggers your vulnerability
    aliases: [invulnerable,invincible,deus,invencivel,invencível,invulnerabel,imortal]
  feed:
    description: Feeds the player
    aliases: [alimentar,tirarfome]
  heal:
    description: Heals the player
    aliases: [curar,life]
  fly:
    description: Makes the player fly
    aliases: [voar]
  day:
    description: Set current world time day
    aliases: [dia]
  night:
    description: Set current world time night
    aliases: [noite]
  tp:
